CrawlingRules/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rules.urls'))
]

rules/urls.py
''' Django URLs '''
from django.urls import path
from rules import views


urlpatterns = [
    path('', views.main, name='main'),
    path('test_view/<int:rule_id>/', views.test_view, name='test_view'),
    path('filter_settings/<int:filter_id>/',
         views.filter_settings, name='filter_settings'),
    path('attr_settings/<int:attr_id>/',
         views.attr_settings, name='attr_settings')
]

rules/models.py
''' Django DB Models '''
from django.db import models


class Rule(models.Model):
    ''' URL Crawling Rule Declaration '''
    url = models.CharField(max_length=1000)


class Filter(models.Model):
    ''' Tag Filters of Crawling Rule '''
    tag_name = models.CharField(max_length=30)
    origin_rule = models.ForeignKey(Rule, on_delete=models.CASCADE)
    find_all = models.BooleanField()


class Attribute(models.Model):
    ''' Attributes of Tag in Filters  '''
    name = models.CharField(max_length=30)
    value = models.CharField(max_length=30)
    origin_filter = models.ForeignKey(Filter, on_delete=models.CASCADE)

rules/forms.py
''' Django Forms of rules '''
from django import forms
from rules.models import Filter, Attribute


class FilterForm(forms.ModelForm):
    ''' Form of <Filter> '''
    class Meta:
        model = Filter
        fields = ('tag_name', 'find_all')
        widgets = {
            'tag_name': forms.TextInput(attrs={'class': 'form-control'}),
            'find_all': forms.CheckboxInput(attrs={'class': 'form-ckeck-input'})
        }


class AttributeForm(forms.ModelForm):
    ''' Form of <Attribute> '''
    class Meta:
        model = Attribute
        fields = ('name', 'value')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'value': forms.TextInput(attrs={'class': 'form-control'})
        }

rules/views.py
''' views.py: Page view methods and some tool functions '''
import urllib.request
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.clickjacking import xframe_options_exempt
from django.urls import reverse

from bs4 import BeautifulSoup

from rules.models import Rule, Filter, Attribute
from rules.forms import FilterForm, AttributeForm


def main(request):
    ''' main page rendering function '''

    url_save_successful = 0  # this value is rule's id
    # this value is first shown rule page
    if Rule.objects.exists():
        rule_page = Rule.objects.order_by('id').first().id
    else:
        rule_page = None

    if request.method == 'GET' and 'rule_page' in request.GET:
        # Load GET parameters (/?rule_page=??)
        rule_page = int(request.GET['rule_page'])

    if request.method == 'POST':
        if request.POST['rules_submit'] == 'set_url':
            # URL related POST Request
            rule_id = int(request.POST['rule_id'])
            rule = get_object_or_404(Rule, id=rule_id)
            rule.url = request.POST['rule_url']
            rule.save()
            url_save_successful = rule_id
            rule_page = rule_id

        if request.POST['rules_submit'] == 'add_rule':
            # Add new rule related POST Request
            new_rule = Rule.objects.create()
            return HttpResponseRedirect(reverse('main') + '?rule_page=%s' % new_rule.id)

        if request.POST['rules_submit'] == 'add_filter':
            # Add new filter related POST Request
            rule_id = int(request.POST['rule_id'])
            Filter.objects.create(
                origin_rule=Rule.objects.get(id=rule_id),
                tag_name=request.POST['addFilterTagName'],
                find_all=False
            )
            return HttpResponseRedirect(reverse('main') + '?rule_page=%s' % rule_id)

        if request.POST['rules_submit'] == 'remove_rule':
            # Remove the rule related POST Request
            rule_id = int(request.POST['rule_id'])
            rule = get_object_or_404(Rule, id=rule_id)
            filts_in_rule = Filter.objects.filter(origin_rule=rule)
            for filt in filts_in_rule:
                attrs_in_filter = Attribute.objects.filter(origin_filter=filt)
                for att in attrs_in_filter:
                    att.delete()
                filt.delete()
            rule.delete()
            return redirect('main')

    context = {
        'rules': Rule.objects.all(),
        'url_save_successful': url_save_successful,
        'rule_page': rule_page
    }

    return render(request, 'sites/rules.html', context)


@xframe_options_exempt
def test_view(request, rule_id):
    ''' test view function '''
    return HttpResponse(content=crawling(rule_id))


def filter_settings(request, filter_id):
    ''' filter settings page rendering function '''

    filt = get_object_or_404(Filter, id=filter_id)
    filtform = FilterForm(request.POST or None, instance=filt)

    if request.method == 'POST':
        if request.POST['filter_submit'] == 'save_filter' and filtform.is_valid():
            # Save filter settings related POST request
            rule_id = filt.origin_rule.id
            filtform.save()
            return HttpResponseRedirect(reverse('main') + '?rule_page=%s' % rule_id)

        if request.POST['filter_submit'] == 'add_attribute':
            # Create new filter's attribute related POST request
            name = request.POST['createAttrName']
            value = request.POST['createAttrValue']
            origin_filt = Filter.objects.get(id=filter_id)
            Attribute.objects.create(
                name=name, value=value, origin_filter=origin_filt)
            return redirect('filter_settings', filter_id=filter_id)

        if request.POST['filter_submit'] == 'delete_filter':
            # Delete filter related POST request
            attrs_in_filter = Attribute.objects.filter(origin_filter=filt)
            for att in attrs_in_filter:
                att.delete()
            rule_id = filt.origin_rule.id
            filt.delete()
            return HttpResponseRedirect(reverse('main') + '?rule_page=%s' % rule_id)

    context = {
        'filter': filt,
        'form': filtform
    }

    return render(request, 'sites/filter_settings.html', context)


def attr_settings(request, attr_id):
    ''' attribute settings page rendering function '''

    attr = get_object_or_404(Attribute, id=attr_id)
    attrform = AttributeForm(request.POST or None, instance=attr)

    if request.method == 'POST':
        if request.POST['attr_submit'] == 'save_attribute' and attrform.is_valid():
            # Save attribute settings related POST request
            rule_id = attr.origin_filter.origin_rule.id
            attrform.save()
            return HttpResponseRedirect(reverse('main') + '?rule_page=%s' % rule_id)

        if request.POST['attr_submit'] == 'delete_attribute':
            # Delete attribute related POST request
            rule_id = attr.origin_filter.origin_rule.id
            attr.delete()
            return HttpResponseRedirect(reverse('main') + '?rule_page=%s' % rule_id)

    context = {
        'attribute': attr,
        'form': attrform
    }

    return render(request, 'sites/attr_settings.html', context)


def crawling(id_idx):
    ''' Crawling method with django models '''
    # get first rule
    my_rule = Rule.objects.get(id=id_idx)

    # init bs4 -> data (soup)
    external_http = urllib.request.urlopen(my_rule.url)
    whole_html = external_http.read()
    data = BeautifulSoup(whole_html, 'html.parser')

    # finding process with filters
    my_filters = Filter.objects.filter(origin_rule=my_rule)
    for filt in my_filters:
        my_attributes = Attribute.objects.filter(origin_filter=filt)
        att_dict = {}
        for att in my_attributes:
            att_dict[att.name] = att.value

        if filt.find_all:
            data = data.find_all(filt.tag_name, att_dict)
        else:
            data = data.find(filt.tag_name, att_dict)

    return str(data)

rules/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'bootstrap-4.4.1-dist/css/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.bundle.min.js' %}"></script>
    <title> Crawling Rules </title>
</head>

<body>
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col">
                <h1 class="mt-2">Crawling Rules</h1>
                <hr class="mt-0 mb-4">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>

</html>

rules/templates/sites/attr_settings.html
{% extends 'base.html' %}

{% block content %}
<h3>Attribute Settings</h3>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="btn-group" role="group">
        <button type="submit" class="btn btn-primary" name="attr_submit" id="save_attribute" value="save_attribute">Save</button>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteAttributeModal">Delete</button>
        <button type="button" class="btn btn-secondary" onclick="window.history.back()">Cancel</button>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="deleteAttributeModal" tabindex="-1" role="dialog" aria-labelledby="deleteAttributeModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteAttributeModalLabel">Delete Attribute</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this attribute?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger" name="attr_submit" id="delete_attribute" value="delete_attribute">Yes</button>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock content %}

rules/templates/sites/filter_settings.html
{% extends 'base.html' %}

{% block content %}

<button type="button" class="btn btn-secondary" id="back" onclick="location.href='{% url 'main' %}?rule_page={{ filter.origin_rule.id }}'">Back to main</button>

<hr>

<!-- filter settings -->
<h3>Filter Settings</h3>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="btn-group" role="group">
        <button type="submit" class="btn btn-primary" name="filter_submit" id="save_filter" value="save_filter">Save</button>
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteFilterModal">Delete</button>
    </div>

    <!-- Modal of deletion -->
    <div class="modal fade" id="deleteFilterModal" tabindex="-1" role="dialog" aria-labelledby="deleteFilterModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteFilterModalLabel">Delete Filter</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete this filter?</p>
                    <p>(All of attributes in the filter will be removed.)</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger" name="filter_submit" id="delete_filter" value="delete_filter">Yes</button>
                </div>
            </div>
        </div>
    </div>
</form>

<hr>

<!-- attributes -->
<h3>Attributes</h3>
<div class="list-group list-group-horizontal d-inline-flex" id="att_{{ filter.id }}">
    {% for att in filter.attribute_set.all %}
    <a href="{% url 'attr_settings' att.id %}" class="list-group-item list-group-item-action">
        {{ att.name }}="{{ att.value }}"
    </a>
    {% endfor %}
</div>
<br><br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#CreateAttrModal">
    Create a new Attribute
</button>

<!-- Modal of creation -->
<form method="POST">
    {% csrf_token %}
    <div class="modal fade" id="CreateAttrModal" tabindex="-1" role="dialog" aria-labelledby="CreateAttrModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="CreateAttrModalLabel">Create a new Attribute</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <div class="form-group">
                        <label for="createAttrInputName">Name</label>
                        <input type="text" class="form-control" id="createAttrInputName" name="createAttrName">
                    </div>
                    <div class="form-group">
                        <label for="createAttrInputValue">Value</label>
                        <input type="text" class="form-control" id="createAttrInputValue" name="createAttrValue">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" name="filter_submit" id="add_attribute" value="add_attribute">Create</button>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock content %}

rules/templates/sites/rule_page.html
{% if url_save_successful == rule.id %}
<div class="alert alert-success" role="alert">
    URL changed successfully.
</div>
{% endif %}

<form method="POST">
    {% csrf_token %}
    <input type="hidden" name="rule_id" id="rule_id_{{ rule.id }}" value="{{ rule.id }}">
    <!-- Input URL -->
    <div class="form-group">
        <label for="InputURL">Site URL To Crawl</label>
        <input type="text" class="form-control" id="InputURL_{{ rule.id }}" name="rule_url" placeholder="Input URL"
            value="{{ rule.url }}">
    </div>
    <div class="btn-group" role="group">
        <button type="submit" class="btn btn-primary" name="rules_submit" id="set_url_{{ rule.id }}"
            value="set_url">Save</button>
        <button type="button" class="btn btn-danger" data-toggle="modal"
            data-target="#RemoveRuleModal{{ rule.id }}">Remove This Rule</button>
    </div>

    <!-- Modal of deletion -->
    <div class="modal fade" id="RemoveRuleModal{{ rule.id }}" tabindex="-1" role="dialog"
        aria-labelledby="RemoveRuleModalLabel{{ rule.id }}" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="RemoveRuleModalLabel{{ rule.id }}">Remove Rule</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete this rule?</p>
                    <p>(All of filters and attributes will be removed.)</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger" name="rules_submit" id="remove_rule_{{ rule.id }}"
                        value="remove_rule">Yes</button>
                </div>
            </div>
        </div>
    </div>
</form>

<hr>
<h5>Filters</h5>

<!-- Filter Buttons -->
<button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#AddFilterModal{{ rule.id }}">Add
    Filter</button>

<!-- Modal of filter addition -->
<form method="POST">
    {% csrf_token %}
    <div class="modal fade" id="AddFilterModal{{ rule.id }}" tabindex="-1" role="dialog"
        aria-labelledby="AddFilterModalLabel{{ rule.id }}" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="AddFilterModalLabel{{ rule.id }}">Add a new Filter</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <input type="hidden" name="rule_id" id="add_filt_rule_id_{{ rule.id }}" value="{{ rule.id }}">
                    <div class="form-group">
                        <label for="addFilterInputTagName_{{ rule.id }}">Tag Name</label>
                        <input type="text" class="form-control" id="addFilterInputTagName_{{ rule.id }}"
                            name="addFilterTagName">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" name="rules_submit" id="add_filter_{{ rule.id }}"
                        value="add_filter">Add</button>
                </div>
            </div>
        </div>
    </div>
</form>

<!-- Filters List -->
{% for filt in rule.filter_set.all %}
<br>
<div class="list-group list-group-horizontal d-inline-flex p-2" id="filter_{{ filt.id }}">
    <!-- tag name -->
    <a href="{% url 'filter_settings' filt.id %}"
        class="list-group-item list-group-item-action list-group-item-{% if filt.find_all %}primary{% else %}secondary{% endif %}">
        {{ filt.tag_name }}
    </a>

    <!-- attributes -->
    {% for att in filt.attribute_set.all %}
    <a href="{% url 'attr_settings' att.id %}" class="list-group-item list-group-item-action">
        {{ att.name }}="{{ att.value }}"
    </a>
    {% endfor %}
</div>
{% endfor %}

<hr>

<!-- Result -->
<h5>Result</h5>
<!-- Show Buttons -->
<div class="btn-group" role="group">
    <button type="button" class="btn btn-light"
        onclick="loadIframe('{{ rule.id }}', '{% url 'test_view' rule.id %}')">Show Result</button>
    <button type="button" class="btn btn-light" onclick="loadHTML('{{ rule.id }}')">Show HTML Code</button>
</div>
<!-- Result Show Views -->
<iframe id="result_{{ rule.id }}" width="100%" height="200">Sorry, iframe
    does not
    support.</iframe>
<textarea class="form-control" id="printBox_{{ rule.id }}" rows="7" disabled></textarea>

rules/templates/sites/rules.html
{% extends 'base.html' %}

{% block content %}

<script>
    function loadHTML(rule_id) {
        // load HTML code of iframe (crawling result)
        var iframe = document.getElementById("result_" + rule_id);
        var printBox = document.getElementById("printBox_" + rule_id);
        printBox.value = iframe.contentWindow.document.body.innerHTML;
    }

    function loadIframe(rule_id, src) {
        // load crawling result URL in iframe
        var iframe = document.getElementById("result_" + rule_id);
        iframe.src = src;
    }
</script>

<form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary" name="rules_submit" id="add_rule" value="add_rule">Add Rule</button>
</form>

<hr>

<div class="row">
    <div class="col-3">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            {% for rule in rules %}
            <a class="nav-link{% if rule.id == rule_page %} active{% endif %}" id="v-pills-rule{{ rule.id }}-tab"
                data-toggle="pill" href="#v-pills-rule{{ rule.id }}" role="tab"
                aria-controls="v-pills-rule{{ rule.id }}"
                aria-selected="{% if rule.id == rule_page %}true{% else %}false{% endif %}">
                Rule {{ rule.id }}
            </a>
            {% endfor %}
        </div>
    </div>
    <div class="col-9">
        <div class="tab-content" id="v-pills-tabContent">
            {% for rule in rules %}
            <div class="tab-pane fade{% if rule.id == rule_page %} show active{% endif %}"
                id="v-pills-rule{{ rule.id }}" role="tabpanel" aria-labelledby="v-pills-rule{{ rule.id }}-tab">
                {% include "sites/rule_page.html" with rule=rule url_save_successful=url_save_successful %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}